import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, BarChart3, BookOpenText, CheckCircle2, FileClock, Gauge, Keyboard, Languages, Sparkles, Target } from 'lucide-react';
import { api } from '../services/api.js';
import { Loader } from '../components/Loader.jsx';
import { Notice } from '../components/Toast.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { StatCard } from '../components/dashboard/StatCard.jsx';
import { ExamCard } from '../components/dashboard/ExamCard.jsx';
import { QuickAction } from '../components/dashboard/QuickAction.jsx';

export default function Dashboard() {
  const { user } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [exams, setExams] = useState([]); const [summary, setSummary] = useState({ totalTests: 0, bestWpm: 0, averageAccuracy: 0 }); const [recent, setRecent] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api('/exams'), api('/results')]).then(([examData, resultData]) => { setExams(examData.exams); setSummary(resultData.summary); setRecent(resultData.results.slice(0, 3)); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!loading && location.hash === '#exams') requestAnimationFrame(() => document.getElementById('exams')?.scrollIntoView()); }, [loading, location.hash]);
  const practices = useMemo(() => ({ english: exams.find((item) => item.name === 'English Typing Practice') || exams.find((item) => item.language === 'English'), hindi: exams.find((item) => item.name === 'Hindi Typing Practice') || exams.find((item) => item.language === 'Hindi') }), [exams]);
  const examQuery = new URLSearchParams(location.search).get('q')?.trim().toLowerCase() || '';
  const filteredExams = useMemo(() => {
    if (!examQuery) return exams;
    return exams.filter((exam) => [exam.name, exam.organization, exam.category, exam.language, exam.description].some((value) => String(value || '').toLowerCase().includes(examQuery)));
  }, [examQuery, exams]);
  if (loading) return <Loader label="Preparing your dashboard…" />;
  return <><section className="student-welcome"><div><span className="welcome-kicker"><Sparkles size={14} />Your practice space</span><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p>Pick up where you left off and keep every keystroke intentional.</p></div><button className="welcome-action" onClick={() => document.getElementById('exams')?.scrollIntoView({ behavior: 'smooth' })}>Explore tests <ArrowRight size={18} /></button></section><Notice>{error}</Notice>
    <section className="student-stats" aria-label="Performance summary"><StatCard icon={FileClock} label="Total tests taken" value={summary.totalTests} tone="blue" /><StatCard icon={Gauge} label="Best net speed" value={`${summary.bestWpm} WPM`} tone="violet" /><StatCard icon={Target} label="Average accuracy" value={`${summary.averageAccuracy}%`} tone="green" /><StatCard icon={BookOpenText} label="Available exams" value={exams.length} tone="amber" /></section>
    <div className="dashboard-columns"><section><div className="section-heading"><div><span>Shortcuts</span><h2>Quick actions</h2></div></div><div className="quick-actions"><QuickAction to="/dashboard#exams" icon={Keyboard} label="Start new test" detail="Choose any exam" /><QuickAction to={practices.english ? `/test/${practices.english._id}` : '/dashboard#exams'} icon={Languages} label="Practice English" detail="Build rhythm and speed" tone="violet" /><QuickAction to={practices.hindi ? `/test/${practices.hindi._id}` : '/dashboard#exams'} icon={Languages} label="Practice Hindi" detail="Improve Hindi accuracy" tone="green" /><QuickAction to="/results" icon={BarChart3} label="View results" detail="Review past attempts" tone="amber" /></div></section>
      <section><div className="section-heading"><div><span>Latest activity</span><h2>Recent results</h2></div>{recent.length > 0 && <button onClick={() => navigate('/results')}>View all <ArrowRight /></button>}</div>{recent.length ? <div className="recent-results">{recent.map((result) => <button key={result._id} onClick={() => navigate(`/result/${result._id}`)}><span className="recent-result-icon"><CheckCircle2 /></span><span><strong>{result.exam?.name || 'Typing test'}</strong><small>{new Date(result.createdAt).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}</small></span><b>{result.netWpm}<small> WPM</small></b></button>)}</div> : <div className="dashboard-empty"><span><Keyboard /></span><div><strong>Your first result starts here</strong><p>Complete a typing test and your performance summary will appear in this space.</p></div><button onClick={() => document.getElementById('exams')?.scrollIntoView({ behavior: 'smooth' })}>Take a test</button></div>}</section></div>
    <section id="exams" className="available-exams"><div className="section-heading"><div><span>Practice library</span><h2>Available exams</h2><p>Exam-style tests designed for focused, distraction-free practice.</p></div><span className="exam-count">{examQuery ? `${filteredExams.length} shown` : `${exams.length} active`}</span></div><div className="student-exam-grid">{filteredExams.map((exam) => <ExamCard key={exam._id} exam={exam} onStart={() => navigate(`/test/${exam._id}`)} />)}</div>{!exams.length && <div className="dashboard-empty"><span><Keyboard /></span><div><strong>No active exams right now</strong><p>Your administrator is preparing new tests. Please check again shortly.</p></div></div>}{exams.length > 0 && !filteredExams.length && <div className="dashboard-empty"><span><Keyboard /></span><div><strong>No exams match your search</strong><p>Try searching by exam name, organization, language or category.</p></div></div>}</section></>;
}
